### ISSUE TITLE
Postgres NOTIFY LISTEN Case study

### ISSUE THREAD

**Issue by r-peter** [nurkiewicz/rxjava-book-examples#4]
Is it possible to add the code snippet in this repo for Postgres NOTIFY LISTEN Case study presented in Chapter 5 of the book, where we could reuse the same connection across multiple multiple subscribers who are interested in different channels?

**Comment by nurkiewicz** [comment]
Hi, I don't have a full source code for this example, sorry. But if you manage to get it working with multiple channels, it would be awesome if you could publish it somewhere. Good luck!
